<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>target/obj/$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <BaseOutputPath>target</BaseOutputPath>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
</Project>
